#        _                 _ _   _
#   __ _| | __ _  ___ _ __(_) |_| |_ _   _
#  / _` | |/ _` |/ __| '__| | __| __| | | |
# | (_| | | (_| | (__| |  | | |_| |_| |_| |
#  \__,_|_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                    |___/

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Fira Mono
    # Style can be specified to pick a specific face.
    style: Medium

  # The bold font face
  bold:
    family: Fira Mono
    # Style can be specified to pick a specific face.
    #
    #style: Bold

  # The italic font face
  italic:
    family: Fira Mono
    # Style can be specified to pick a specific face.
    style: Regular
  size: 10.0

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x323732'
    foreground: '0xebdbb2'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  cursor:
    text: '0x44475a'
    cursor: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x222422'
    red:     '0xcc241d'
    green:   '0x1e8f73'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x207571'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x606660'
    red:     '0xfb4934'
    green:   '0x80C6A4'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x2B9E99'
    white:   '0xebdbb2'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #black:   '0x14151b'
  # red:     '0xff2222'
  # green:   '0x1ef956'
  # yellow:  '0xebf85b'
  # blue:    '0x4d5b86'
  # magenta: '0xff46b0'
  # cyan:    '0x59dffc'
  # white:   '0xe6e6d1'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  indexed_colors: []


background_opacity: 1

env:
        TERM: xterm-256color

window:
        dimesions:
                columns: 0
                lines:  0
        padding:
                x: 10
                y: 10
        dynamic_padding: false
        decorations: full

tabspace: 4

draw_bold_text_with_bright_colors: true

mouse:
        hechidden_when_typing: true

dynamic_title: true
